//
//  KMAssets.h
//  KMSDK
//
//  Created by cb on 4/4/16.
//  Copyright (c) 2016 Kiswe Mobile. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface KMAssets : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_back_10_secsCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_backCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_closeCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_forward_10_secsCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_hide_controls_whiteCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_hide_controlsCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_hide_pips_whiteCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_hide_pipsCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_info_activeCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_infoCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_pauseCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_play_by_play_activeCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_play_by_playCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_playCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_show_controls_whiteCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_show_controlsCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_show_pips_whiteCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_show_pipsCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_stats_activeCanvasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* icon_statsCanvasTargets;

// Drawing Methods
+ (void)drawIcon_back_10_secsCanvas;
+ (void)drawIcon_backCanvas;
+ (void)drawIcon_closeCanvas;
+ (void)drawIcon_forward_10_secsCanvas;
+ (void)drawIcon_hide_controls_whiteCanvas;
+ (void)drawIcon_hide_controlsCanvas;
+ (void)drawIcon_hide_pips_whiteCanvas;
+ (void)drawIcon_hide_pipsCanvas;
+ (void)drawIcon_info_activeCanvas;
+ (void)drawIcon_infoCanvas;
+ (void)drawIcon_next_pageCanvas;
+ (void)drawIcon_pauseCanvas;
+ (void)drawIcon_play_by_play_activeCanvas;
+ (void)drawIcon_play_by_playCanvas;
+ (void)drawIcon_playCanvas;
+ (void)drawIcon_previous_pageCanvas;
+ (void)drawIcon_show_controls_whiteCanvas;
+ (void)drawIcon_show_controlsCanvas;
+ (void)drawIcon_show_pips_whiteCanvas;
+ (void)drawIcon_show_pipsCanvas;
+ (void)drawIcon_stats_activeCanvas;
+ (void)drawIcon_statsCanvas;

// Generated Images
+ (UIImage*)imageOfIcon_back_10_secsCanvas;
+ (UIImage*)imageOfIcon_backCanvas;
+ (UIImage*)imageOfIcon_closeCanvas;
+ (UIImage*)imageOfIcon_forward_10_secsCanvas;
+ (UIImage*)imageOfIcon_hide_controls_whiteCanvas;
+ (UIImage*)imageOfIcon_hide_controlsCanvas;
+ (UIImage*)imageOfIcon_hide_pips_whiteCanvas;
+ (UIImage*)imageOfIcon_hide_pipsCanvas;
+ (UIImage*)imageOfIcon_info_activeCanvas;
+ (UIImage*)imageOfIcon_infoCanvas;
+ (UIImage*)imageOfIcon_pauseCanvas;
+ (UIImage*)imageOfIcon_play_by_play_activeCanvas;
+ (UIImage*)imageOfIcon_play_by_playCanvas;
+ (UIImage*)imageOfIcon_playCanvas;
+ (UIImage*)imageOfIcon_show_controls_whiteCanvas;
+ (UIImage*)imageOfIcon_show_controlsCanvas;
+ (UIImage*)imageOfIcon_show_pips_whiteCanvas;
+ (UIImage*)imageOfIcon_show_pipsCanvas;
+ (UIImage*)imageOfIcon_stats_activeCanvas;
+ (UIImage*)imageOfIcon_statsCanvas;

@end
