//
//  NascarTrackCharlotteMotorSpeedway.h
//  TrekkerLive
//
//  Created by Chris Boraski on 11/5/15.
//  Copyright (c) 2015 Kiswe Mobile. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface NascarTrackCharlotteMotorSpeedway : NSObject

// Drawing Methods
+ (void)drawTrack;

@end
